rewrite cache system

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,13 +2,37 @@ name: Build TelegramNotifier
 
 on:
   push:
-    branches:
-      - main
   pull_request:
-    branches:
-        - main
+
 
 jobs:
+
+  php-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      
+      - name: PHP Syntax Check
+        run: |
+          find . -name "*.php" -print0 | xargs -0 -n1 php -l
+          if [ $? -ne 0 ]; then
+            echo "PHP syntax check failed"
+            exit 1
+          fi
+
+  markdown-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Lint Markdown files
+        uses: DavidAnson/markdownlint-cli2-action@v19
+        with:
+          globs: '**/*.md' # Checks all Markdown files in the repository
+          fix: true # automatically fixes simple problems
+          config: '.markdownlint.jsonc'  # if you have a configuration file
+#        continue-on-error: true  # to prevent the build from crashing due to errors in the documentation
+
   build:
     runs-on: ubuntu-latest
     steps:
